Repository finleap-connect/monoctl, pull requests merged in 2022-06, with the labels that each got.

#76 Add auto-approve and merge via dependabot
  .github/workflows/dependabot-auto-approve.yaml
  .github/workflows/dependabot-auto-merge.yaml
Labels: feature

#77 Add linux arm build
  go.mk
Labels: feature

#80 Fix audit log get by user returns user actions
  cmd/monoctl/get/audit_log_by_user.go
Labels: bug

#81 Update workflow
  .github/workflows/golang.yaml
  go.mk
  internal/usecases/get_cluster_credentials.go
Labels: chore

#79 Kubeconfig based on ClusterAccess
  go.mk
  go.mod
  go.sum
  internal/usecases/create_cluster.go
  internal/usecases/create_cluster_test.go
  internal/usecases/create_kubeconfig.go
  internal/usecases/create_kubeconfig_test.go
  internal/usecases/create_rolebinding.go
  internal/usecases/expected_m8_operator_bootstrap.yaml
  internal/usecases/get_clusters_test.go
  internal/usecases/m8_operator_bootstrap.yaml
  test/mock/domain/certificate_client.go
  test/mock/domain/cluster_client.go
Labels: feature

#86 Readme contains nonsense about gitlab
  README.md
  docs/Makefile.md
Labels: bug, chore

#87 Fix permission bug in monoctl
  internal/usecases/create_kubeconfig.go
  internal/usecases/get_cluster_credentials.go
  internal/usecases/get_cluster_credentials_test.go
Labels: bug
